[build]
  command = "npm run build" # Adjust to match your build process
  publish = "dist"          # Replace with your build output directory

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"  # Optional: Use "esbuild" for smaller and faster builds

[functions."email-service"]
  schedule = "*/15 * * * *" # Cron expression for every 15 minutes
